### ISSUE TITLE
Please support terraform imports

### ISSUE THREAD

**Issue by djhaskin987-at-sling** [ericchiang/terraform-provider-k8s#10]
This is in follow up to PR #9. 

I work at SlingTV. I am on an 8 person DevOps team. We support our developers, which at my estimation amount to something like 250+ engineers. We also support our ops team, who are responsible for the deployment of our backend software.

Our app deployment is large, and relies heavily on VMware, SaltStack, SSH, and even some manual deployment steps currently.

We are also in the early stages of putting our deployments into kubernetes. We already have several apps in k8s.

I would like to bring a large portion of our deployments under management by Terraform. However, if I can't import what is already deployed using old or undesirable technologies into Terraform state  without affecting already-live deployments, putting stuff into TF is going to be a hard sell to my ops team. Likewise, if I can't re-create the TF state (if it were ever lost) without the need to touch current deployments, my Ops team probably won't let me introduce a new, never-before-used tool into their environment.

Fortunately, `terraform import` allows for both use cases as described above. It exactly fits what I need to make sure that I can convince them to use terraform in our broader deployment strategy.

The only plugin that is even *close* to handling kubernetes deloyments right is, in my opinion, this one. It allows me to use CRDs and I don't have to wait for the the official kubernetes provider to support the workloads API.

I would like `terraform import` to be supported with this plugin. This way I can make sure I can recover if terraform state were ever deleted without actually touching any live deployments. This will also allow me to write new terraform states, then import what I already have deployed into terraform, again without touching the live deploy.

I would use terraform import like this:

```
terraform import k8s_manifest.nginx-deployment /apis/extensions/v1beta1/namespaces/default/deployments/releaseme-example
```

That is, I would give terraform an ID of a live deployment and point to what terraform resource stanza I had written to tell TF what code should manage the live deploy in the future.

All that is required for that to work is to have the provider support what is known as an "id-only refresh", meaning that it has to be able to repopulate all of the attributes of the resource in its `resourceManifestRead` function. So, if we can change that function to repopulate "content" based on what is actually already deployed, importing will work simply by adding some boilerplate just-use-the-read-function passthrough code when creating the `Resource` struct and passing to terraform in the provider.

This is the approach I took in #9 . I simply read in from a k8s annotation what was previously given to kubectl in a `kubectl apply` call. I also normalized the contents of the "contents" value so that diffs between what terraform reads in production and what terraform was given would make sense, and wouldn't just be over something like whitespace or quotes.

**Comment by djhaskin987-at-sling** [comment]
For anyone interested, I have merged the PR in question to the fork here if you want to see how it works -> https://github.com/djhaskin987-at-sling/terraform-provider-k8s

It should be backwards compatible with deployments using this plugin :)

**Comment by ericchiang** [comment]
Here are some thoughts:

* This would require manifests to previously be deployed using `kubectl apply`, not `kubectl create`.
* `kubectl apply` does comparison of the annotation and the manifests. It's already no-op if the data hasn't changed.
* As it stands, to do `terraform import` you already have to create equivalent resources.

So today, to add existing resources on a cluster to your terraform state file you would:

* Define your manifests in terraform.
* Run `terraform apply`:
  * If manifests are different terraform applies the new resource.
  * If manifests the same `kubectl apply` is no-op but returns the IDs to terraform.

Where if we added import, you would still:

* Define your manifests in terraform.
* Run `terraform import` to load resources into your state file.
* Run `terraform apply`
  * If manifests are different terraform applies the new resource.
  * If manifests the same (determine by terraform comparing the `kubectl apply` annotation) this is no-op.

Since `kubectl apply` already does a no-op if the manifests haven't changed, why isn't that the recommended way of bringing existing resources under management `kubectl apply`'ing over them? I don't see a huge amount of gain for the increased complexity.

**Comment by ericchiang** [comment]
I'd also argue that your state is in your manifests if you lose your tfstate files :)

To further this conversation, I think you're right to focus on "how to recover from state loss." I'm just not convinced that `terraform import` is the right way.

**Comment by djhaskin987-at-sling** [comment]
I experimented on your argument and it worked.

I went into the examples/ directory in this repo and applied terraform state. Then I deleted the tfstate files and re-applied. Things worked fine.

Thanks for hearing me out :)

**Comment by ericchiang** [comment]
Thanks for the patience and glad it worked!
